### ISSUE TITLE
tweets out the same price?

### ISSUE THREAD

**Issue by ssithuxz** [ryanc20/crypto-twitter-bot#1]
it keeps tweeting the same price every interval

doesn't update using API

**Comment by ryanc20** [comment]
Thanks for letting me know, I think the issue is that the values for each price and the message are stored prior to the loop and are never updated within the loop. I will add those values inside the while loop and it should work correctly.

EDIT: I have updated the code, it should work correctly.

**Comment by ssithuxz** [comment]
Looks good !
